In [1]:
import numpy as np

In [2]:
'''1D array'''
arr=np.array([6,4,3,2])

In [3]:
arr

array([6, 4, 3, 2])

In [4]:
arr[0]

np.int64(6)

In [7]:
'''2D array'''
arr1=np.array([[6,7,8,9],[1,2,3,4]])

In [8]:
arr1

array([[6, 7, 8, 9],
       [1, 2, 3, 4]])

In [9]:
type(arr1)

numpy.ndarray

In [11]:
arr1.dtype

dtype('int64')

In [13]:
arr1.shape

(2, 4)

In [15]:
'''Array creation using intrinsic methods'''
arr2=np.zeros((2,5))

In [16]:
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng=np.arange(5)

In [18]:
rng

array([0, 1, 2, 3, 4])

In [19]:
lspace=np.linspace(1,5,4)

In [20]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
ide=np.identity(5)

In [23]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
rng1=np.arange(56)

In [25]:
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [29]:
rng1=rng1.reshape(2,28)

In [30]:
rng1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]])

In [32]:
rng1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [33]:
'''axis in numpy'''
l=[[1,2,3],[4,5,6],[7,1,0]]

In [34]:
l

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [35]:
a=np.array(l)

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
n=a.sum(axis=0)

In [39]:
n

array([12,  8,  9])

In [40]:
'''Transpose of array'''
print(a.T)

[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [42]:
'''T show dimensions'''
a.ndim

2

In [45]:
'''this gives the index not the value'''
n1=np.array([44,2,11,3])
n1.argmax()


np.int64(0)

In [47]:
'''Broadcasting in numpy'''
a1=np.array([4,3,1])
print(a1)
a2=np.array([1,1,1])
print(a2)

[4 3 1]
[1 1 1]


In [48]:
a1+a2

array([5, 4, 2])

In [50]:
a1=np.array([4,3,1])
print(a1)
a2=np.array([[1],[1],[1]])
print(a2)

[4 3 1]
[[1]
 [1]
 [1]]


In [51]:
a1+a2

array([[5, 4, 2],
       [5, 4, 2],
       [5, 4, 2]])